### ISSUE TITLE
IMU object missing freq, name, and unit(s)

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#102]
**Issue:**

`imu()` object needs to mirror a `gts()` object with slightly more structure.

**Solution**

Add following components:

1. freq - frequency of data
2. name - data set
3. unit(s) - I think this should be singular (e.g. `'sec'`)

This means that the graphing procedures should also appropriately update (e.g. wvar, gmwm, auto.imu) to handle the freq change.

**Comment by Wenchao-Yang** [comment]
It's done.
