### ISSUE TITLE
Label columns with names

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#103]
**Issue:**

gmwm data objects (`gts`,`imu`,`lts`) do not have column names. 

**Solution:**
Add column names

1. gts
if not empty: name else "observed"
2. imu
"Gyro-X","Gyro-Y",..,"Accel-Z"
3. lts
if name not empty: name else "sum"
"P1.AR1","P2.WN",...,"PN:X", name

**Comment by Wenchao-Yang** [comment]
It's done.
