### ISSUE TITLE
Data Obj Structure Change

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#108]
**Issue**

Data objects: `imu`, `gts`, `lts` are locked behind a list structure. 

This impacts base R functions, user workflow, and increases additional memory overhead.

**Solution**

Switch over to the new obj structure using attributes via
```r
ex = function(x, freq, name){
 mostattributes(x) = list(freq = freq, name = name,
                                         class="exme")
x
}

m = ex(rnorm(100), 2, "toad")
m
attr(m,"freq")
attr(m,"name")
```

Rewrite functions to use `attr` to access values 
`data$data` => `data`
`data$freq` => `attr(data,"freq")`
`data$name` => `attr(data,"name")`

For data that is one dimensional (e.g. gts, imu) use:
```r

colnames(x) = "Some Name"
  x = structure(x, start = start,
                   end = end, 
                   freq = freq, 
                   unit = unit, 
                   name = name,
                   class= c("gts","matrix")) 
```

Note the inclusion of the "matrix" class.

Otherwise, when adding attributes, the vector is "simplified". 

Using x[drop = F] prevents the attributes from being added.

**Comment by coatless** [comment]
@Wenchao-Yang see updated head issue for data obj fix. Use structure(data, start, end, freq, name, class = c("gts","matrix")).

**Note:**
If property `"start"` is null, then:

```r
attr(x,"start") 
NULL
```

**Comment by Wenchao-Yang** [comment]
It's done.
