### ISSUE TITLE
avar/hvar: base to ggplot2

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#109]
**Issue**

avar & hvar plots need to be switched from base graphics to ggplot2

**Solution**

Work on a ggplot2 implementation of avar / hvar. Reuse wvar plot code?

**Comment by coatless** [comment]
@Wenchao-Yang 

Priority 2.

**Comment by Wenchao-Yang** [comment]
It's done!

**Comment by coatless** [comment]
Added in PR #183
