### ISSUE TITLE
Process Decomp Graph Legend: Summation & Color

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#117]
**Issue:**

Sum of large processes pushes the graph window to be too "small".

Yellow is too hard to read. Any way to remove the yellow color from appearing?

**Solution:**

If the number of processes is > 3 , use:

"Process Sum"

Otherwise, use the current "Process 1 + Process 2 + Process 3" 

Remove the yellow color.

**Comment by Wenchao-Yang** [comment]
1. remove the yellow color (the 5th color) from the palette
2. On the legend, use 'sum'  instead of process names to indicate the sum of different processes.
Example:
```
N = 1000
model = AR1(phi = .54, sigma2 = .99) + WN(sigma2 = 1)
data = gen.gts(model, N)
model3 =  gmwm.imu(8*AR1() + RW(), imu6[,2])
plot(model3, process.decomp = T)
```

**Comment by Wenchao-Yang** [comment]
This is done!
