### ISSUE TITLE
Process Decomp Graph: Revert to Default if 1 Process

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#118]
**Issue:**

If process.decomp = T when there is only 1 process. It does not make sense to show both the decomp process and the summed.

**Solution:**

Just default to showing the summed (e.g. process.decomp = F) graph.

**Comment by Wenchao-Yang** [comment]
Automatically set `process.decomp = F` if there is only 1 process. No warning/message is needed.

**Comment by Wenchao-Yang** [comment]
This is fixed!
