### ISSUE TITLE
auto.imu: Add option for process.decomp

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#119]
**Issue:**

It would be nice to see the theoretical decomposition for the best auto.imu models.

**Solution:**

Grab code from GMWM process.decomp and embed in auto.imu graph.

**Comment by coatless** [comment]
@Wenchao-Yang this needs to get done pronto

**Comment by Wenchao-Yang** [comment]
How it will be implemented:

![img_1363](https://cloud.githubusercontent.com/assets/12223872/13544511/4f2ceed0-e23c-11e5-9b11-64a2fc56abf4.JPG)

**Comment by coatless** [comment]
ETA?

**Comment by Wenchao-Yang** [comment]
Sorry for the delay. Codes have been committed and it's finally done.

**Comment by coatless** [comment]
Addressed by PR #159
