### ISSUE TITLE
expanded imu options

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#125]
**Issue**

Currently, we have to have a gyro and accelerometer of the same axis within the object.  This is problematic as one may want to just include an x-gyro, x-accel, and y-accel. (Note the axis differences)

**Solution**

Instead of having only "Gyroscope" and "Accelerometer" and then one copy of axis x and y... 

Use:

* Gyroscope Accelerometer Accelerometer
* X X Y

**Comment by coatless** [comment]
Per our discussion today, let's extend this way:

```r 
x = imu(data[,c(1,2,4:6)], g=1:2, a=4:6, axis = c("x","y","x","y","z"))
```

Then:

```
attr(x,"sensor") 
 Gyro, Gyro, Accel, Accel, Accel
attr(x,"axis")
 X, Y, X, Y, Z
```

**Comment by Wenchao-Yang** [comment]
This is done!
