### ISSUE TITLE
imu object in compare.wvar

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#128]
**Issue**

wvar.imu does not play nicely with compare.wvar

**Solution**

Require the **imu** object to have column of 1 and graph like normal.

Alternatively, require the same amount of columns in the **imu** object, but graph multiple lines.

**Comment by Wenchao-Yang** [comment]
New plan:
![img_1331](https://cloud.githubusercontent.com/assets/12223872/13192002/b07740a6-d72d-11e5-9796-f30f8992572a.JPG)
Write a new function called compare.wvar.imu(). If the object is a "wvar.imu" object, redirect it to compare.wvar.imu(). User should only need to know compare.wvar().

**Comment by coatless** [comment]
Also, throw an error if one of the inputs is of type `gmwm`.

**Comment by coatless** [comment]
Related to #155 

@Wenchao-Yang Try to knock both of these out at the same time.
