### ISSUE TITLE
Plot of IMU WV

### ISSUE THREAD

**Issue by robertomolinari** [SMAC-Group/gmwm#130]
When plotting the WV of all axes in an IMU dataset (plot(wvar.imu(imu.object))), the lines of gyroscopes and accelerometers appear to be inversed (i.e. gyroscopes should be on the first line and accelerometers on the bottom line of the plot). To check if this is valid for all IMUs (in this case it is IMAR).

**Comment by coatless** [comment]
This has been fixed on the v2.0 line.
