### ISSUE TITLE
gmwm.robust - Simultaneously model Classical & Robust GMWM

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#144]
**Feature:**

For the JSS version, we may wish to support a `gmwm.robust()` version of the `gmwm()`. 
This version in particular should provide > BOTH < the classical and robust estimators of the GMWM.

The motivating case for this is someone who is unfamiliar with modeling between different paradigms is then able to easily see the difference between estimators. E.g. They can know that there data has been contaminated and react appropriately.

Key changes:

1. New `gmwm.*()` function
2. Redirect into `compare.eff()` to graph

**Comment by coatless** [comment]
@Wenchao-Yang important for JSS paper.

**Comment by coatless** [comment]
ETA?

**Comment by Wenchao-Yang** [comment]
I'm testing the code. It should be there soon together with the auto.imu graph.

**Comment by Wenchao-Yang** [comment]
It's done!

**Comment by coatless** [comment]
Addressed by PR #159
