### ISSUE TITLE
autoplot.wvarComp is regarded as one S3 method

### ISSUE THREAD

**Issue by Wenchao-Yang** [SMAC-Group/gmwm#170]
autoplot.wvarComp is regarded as one S3 method, but it shouldn't be.

**Comment by coatless** [comment]
This is normal behavior when we are interfacing with `autoplot.*()` as it is itself an S3 object that is being extended from `ggplot2`.

See: `?autoplot.gmwm1`, `?autoplot.auto.imu1`, ... 


To get around the `autoplot()` showing as an S3, we could demote the call to just:

`graphing_gmwm1(...)`

with the same parameter pass.
