### ISSUE TITLE
IMU Graph Labels

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#175]
**Issue:**

The imu graph labels need to be updated to either:

m^2/(s^4) for accelerometers 

rad^2/s^2 for gyroscope 

This should be done within the `facet`.

**Comment by coatless** [comment]
@Wenchao-Yang 

This is a priority fix.

**Comment by coatless** [comment]
@Wenchao-Yang This will need to be done within the `facet` avoid the rectangle idea. 

Otherwise, we would have to break apart the graph with `arrangeGrobs()`.

**Comment by Wenchao-Yang** [comment]
This is finally done in the facet, since part of y label is hidden if I modify the y label directly.
