### ISSUE TITLE
Negative scales on compare.wvar() graph

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#186]
**Issue:**

Scales are reported incorrectly on `compare.wvar()` with actual data.

```r
library("gmwm")

# devtools::install_github("smac-group/datapkg")

data("hydro", package="datapkg")
wv_hydro = wvar(hydro)

wv_robhydro = wvar(hydro, robust = T)

compare.wvar(wv_hydro, wv_robhydro, split = F)
```

![bug_comparewv](https://cloud.githubusercontent.com/assets/833642/15808716/84cfaa90-2b44-11e6-9610-77eab765bbe6.jpeg)

**Comment by coatless** [comment]
Not really a bug since the scale is being modified by the frequency of the observations. (e.g. 12 observations per year)

**Comment by stephaneguerrier** [comment]
Sorry James… I still don’t get it…

**Comment by coatless** [comment]
Per e-mail, this is expected behavior due to `freq` being set.
