### ISSUE TITLE
installation on windows 7 with latest R and latest RStudio

### ISSUE THREAD

**Issue by philippcla** [SMAC-Group/gmwm#187]
Hello,
When I follow the guide on the smac group for installing the gmwm I have as last instruction:
`gmwm::install_datapkg()`

Unfortunatelly I get this message:
```
> gmwm::install_datapkg()
Installing package into ‘C:/Users/philipp/my_documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://smac-group.com/datarepo/bin/windows/contrib/3.3:
  cannot open URL 'http://smac-group.com/datarepo/bin/windows/contrib/3.3/PACKAGES'
Warning message:
package ‘datapkg’ is not available (for R version 3.3.0)
```

What should I do?
Thanks

**Comment by coatless** [comment]
`datapkg` has yet to be pushed into the [datarepo](http://github.com/smac-group/datarepo). I think we're going to be changing the name to `smacdata` or doing some sort of theme.

**Comment by philippcla** [comment]
ok
