### ISSUE TITLE
compare.gmwm - legend 

### ISSUE THREAD

**Issue by philippcla** [SMAC-Group/gmwm#200]
Hello,

I am using the "compare.gmwm"
When I plot the wvar, the legend is displayed on the right side of the figure, ok.

Now, the size of the title, ticks, .... can all be changed and adapted, ok.

BUT is there a way to place the legend (which is normally placed on the right side) below the figure? Depending on the variable names, the legend takes half of the screenplace, which is superhuge!

Or could I even suppress the automatically generated legend by setting some bool to "FALSE"?

Thx

![rplot01](https://cloud.githubusercontent.com/assets/19432740/18277455/d9e00a7c-744e-11e6-8890-53915fb7898a.png)

**Comment by coatless** [comment]
@philippcla This goes away under the new `compare.gmwm()` paradigm. 

In the interim, you can hide the legend with:

```r
autoplot(gmwm_obj) + theme(legend.position = "none")
```

**Comment by philippcla** [comment]
works like a charm.
ok
thx

**Comment by coatless** [comment]
`compare.gmwm()` was declared defunct gmwm v3.0 in favor of `compare_models()`. Closing out this issue as a result.
