### ISSUE TITLE
memory allocation issue with "summary(estimated_model, inference = T, bs.gof = T)"

### ISSUE THREAD

**Issue by philippcla** [SMAC-Group/gmwm#209]
Hello,

I have a big dataset 2000000x6 values
I create 100 bins, so that means I have bins of 20000x6 values

then I estimate the model and do a summary
This is done in two for loops, one for the bins and one for the 2nd dimension j

The loop works and the calculations are ok individually.
BUT whenever I execute the "summary(estimated_model, inference = T, bs.gof = T)"  it eats 200MB of my RAM, thus I cannot perform the two for loops without reaching my 12GB memory ram imit. Do you know what is happening? This extra 200MB of RAM looks crazy

Here is some code I executed:
  

> for (i in 1:100)
> {
>     
>     index_starts <- i*parts_per_bin - parts_per_bin + 1
>     index_ends <- i*parts_per_bin
>     indexes_to_consider <- seq(from=index_starts, to=index_ends)
>     
>     print(paste("bin", i))
>     
>     # choose the proper model according to the axis
>     for (j in 1:6)
>     {
>       print(paste("axis", j))
>       imu_object <- imu(data = refitted_imu_data[indexes_to_consider,j], acc = 1, freq = 200)
>       wvar<- wvar(imu_object)
>       estimated_model <- gmwm(gmwm_model, imu_object, freq = imu_freq, robust = robust_flag,  seed = seed_number)
>   
>       print(paste("-> print before the summary"))
>       print(paste(system("free -m", intern = TRUE)[cbind2(1,2)]))
>       
>       b <- summary(estimated_model, inference = T, bs.gof = T)
>       
>       print(paste("-> print after the summary"))
>       print(paste(system("free -m", intern = TRUE)[cbind2(1,2)]))
>       
>       # clear everything
>       rm(b ,imu_object, wvar, estimated_model)
>       
>       gc()
>     }
>   }

And the result in the terminal was:

> [1] "bin 1"
> [1] "axis 1"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5436**       6270        590         41       1588"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5540**       6167        590         41       1588"
> 
> [1] "axis 2"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5449**       6258        590         41       1588"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5640**       6067        591         41       1588"
> 
> [1] "axis 3"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5645**       6062        591         41       1589"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5886**       5820        591         41       1589"
> 
> [1] "axis 4"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **5892**       5814        591         41       1589"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6102**       5604        584         41       1583"
> 
> [1] "axis 5"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6108**       5598        584         41       1582"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6319**       5387        584         41       1582"
> 
> [1] "axis 6"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6324**       5382        584         41       1582"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6538**       5168        584         41       1582"
> 
> [1] "bin 2"
> [1] "axis 1"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6543**       5163        584         41       1582"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6757**       4950        584         41       1582"
> 
> [1] "axis 2"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6763**       4943        584         41       1582"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **6977**       4729        584         41       1582"
> 
> [1] "axis 3"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7006**       4700        584         41       1582"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7366**       4340        605         47       1651"
> 
> [1] "axis 4"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7372**       4335        605         47       1651"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7710**       3996        737         47       1784"
> 
> [1] "axis 5"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7716**       3990        737         47       1784"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7799**       3907        609         51       1658"
> 
> [1] "axis 6"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **7801**       3905        609         51       1658"
> [1] "-> print after the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **8003**       3703        610         53       1660"
> 
> [1] "bin 3"
> [1] "axis 1"
> [1] "-> print before the summary"
> [1] "             total       used       free     shared    buffers     cached"
> [2] "Mem:         11707       **8008**       3698        610         53       1660"

It continues to eat 200MB each loop like this until I get the message:

> error: arma::memory::acquire(): out of memory
> Show Traceback
> Rerun with Debug
> Error in summary.gmwm(estimated_model, inference = T, bs.gof = T) : 
> std::bad_alloc

And here is a plot of my memory usage:
![image](https://cloud.githubusercontent.com/assets/19432740/22215528/fd9747c2-e19b-11e6-953e-f876df39fc96.png)

Can you help?

Thanks

**Comment by coatless** [comment]
Yes.  There is a [memory leak associated with the `field` class of Armadillo](https://github.com/conradsnicta/armadillo-code/commit/067347a7cc6697940bc02316b71260810b589c81
) that was release onto CRAN within RcppArmadillo that we depend upon. (e.g. 7.600.1 had the bug and 7.600.2 fixed it)

Please install the development version that has a patch out for it and then rebuild the GMWM library.

```r
devtools::install_github("Rcpp/RcppArmadillo")
devtools::install_github("SMAC-Group/gmwm")
```

**Comment by philippcla** [comment]
I used:
`devtools::install_github("RcppCore/RcppArmadillo")`

It works now like a charm!
You are the chief!! Thanks

**Comment by coatless** [comment]
Great to hear this is working! I'm going to close out this issue.
