### ISSUE TITLE
labels with "space" in compare_models

### ISSUE THREAD

**Issue by philippcla** [SMAC-Group/gmwm#212]
Hello,

I want to correctly label my comparison and I use:
`compare_models(estimated_model_one, estimated_model_two, title = " ", show.theo.wv = T, transparence = 0.2, facet.label = c('first state', 'second state'))`

it gives me the error
`Error in parse(text = as.character(values)) :   <text>:1:6: unexpected symbol 1: first state          ^`

Can't I have labels with a space?

**Comment by Wenchao-Yang** [comment]
Thanks for posting this. The reason why this happens is that the labels are interpreted as plotmath expressions. If you want to put space in labels, please replace space with '~'. 

In your example, try
`compare_models(estimated_model_one, estimated_model_two, title = " ", show.theo.wv = T, transparence = 0.2, facet.label = c('first~~state', 'second~~state'))`

Let me know if there is any other question.

**Comment by Wenchao-Yang** [comment]
@coatless In some functions like compare_models, labels are interpreted as plotmath, so we can show the model details, such as '3*AR1 + RW', in the facet label.

This also means, when user want to specify their labels, they also need to supply plotmath expressions. We can add this to the help doc. If you have other ideas about implementing this feature, let me know.

**Comment by philippcla** [comment]
Ahhh
ok
thx
