### ISSUE TITLE
compare.eff lacks ability to display models with different scales

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#4]
Issue:
compare.eff() (no longer compare.models) is unable to handle models with different scales.

No detection of whether the models supplied are the same object.

Steps needed:
1. Check for whether the objects are the same, then direct to the main gmwm graphing function.
2. Melt the data.frame
3. Rewrite the ggplot plot statements to use the new structure.
4. Add customization options for:
axis title, plot title, axis labels, legend size

1.receive model, vector of eff (0~1), model type('ssn' or 'sensor' )
if no eff, don't generate the graph
2.generate gmwm object (default: generate classical, defualt eff = 0.6)
3.graph:one classical model vs. all robust model

1.fix model, same data
2.vary eff, default is 0.6
3. classical graph by default

**Comment by Wenchao-Yang** [comment]
How it will be implemented

![image1](https://cloud.githubusercontent.com/assets/12223872/13163990/62cef508-d677-11e5-9f48-76890db2560c.JPG)
