### ISSUE TITLE
Add MSFT data set to illustrate compare.wvar

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/gmwm#50]
Add high-freq dataset. Here is a sample code:

library(GMWM)
Xt = read.table("eur_usd.txt")

X1 = Xt[(Xt[,1] == "12.03.2001"),3]
X2 = Xt[(Xt[,1] == "13.03.2001"),3]
X3 = Xt[(Xt[,1] == "14.03.2001"),3]
X4 = Xt[(Xt[,1] == "15.03.2001"),3]
X5 = Xt[(Xt[,1] == "16.03.2001"),3]

Wv1 = wvar(X1)
Wv2 = wvar(X2)
Wv3 = wvar(X3)
Wv4 = wvar(X4)
Wv5 = wvar(X5)

compare.wvar(Wv1,Wv2,Wv3,Wv4,Wv5, split = F, legend.label= c("12.03.2001","13.03.2001","14.03.2001","15.03.2001","16.03.2001") )

I have the data on my computer...

**Comment by coatless** [comment]
How about we put MSFT stock data in a second data package? 

findata

?

**Comment by coatless** [comment]
Added to a general data package

smac/group@09cd71cc104d3b377b85348fc9ff7de4a033407f
