### ISSUE TITLE
compare.models - the "correlation" matrix formulation

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#70]
Okay, so we've updated the specs on #4 since it became apparent that there were too many lines on the graph.

The new specs for this function are:

1. "Correlation" matrix setup. Specifically, the graph is now being broken into an $M x M$ grid, where $M$ represents the number of models under consideration.
    * So, the rows and columns of the matrix should be labeled $M_1$, $M_2$,..., $M_{n}$, where $n$ denotes the total models under consideration.
    * For the time being, we'll cap it at 8 models since the color palate we have is 9. This may change. (Allow for flexibility).
    * As an example, we'll work on a $3x3$ matrix. 
2. On the MAJOR DIAGONAL (e.g. top left to bottom right) of the matrix, the graph should be the default GMWM graph for the model specified.
    * It should contain: WV Empirical, WV CI, and WV Implied.
    * Please save the color used for the WV Implied. This will be used in upper and lower diagonals.
    * The WV CI should have the same color as the WV Empirical. The only difference should be the line type.
    * This should be applied to each row and column that share the same number e.g. 1x1 (model 1), 2x2 (model 2), 3x3 (model 3)
3.  On the LOWER Triangular Matrix Section (e.g. everything below the major diagonal), the graph should be a comparison of the two WV Implied on the GMWM Graph.
    * It should contain: WV Empirical + WV CI. There should be **two** WV Implied. 
    * Please use the same color for each WV Implied that can be found on the diagonal.
    * The WV CI should have the same color as the WV Empirical. The only difference should be the line type.
    * This should be applied to each row and column that share the $i > j$ e.g. 2x1 (model 2 vs. model 1), 3x1 (model 3 vs. model 1), 3x2 (model 3 vs. model 1) 
4. On the UPPER Triangular Matrix Section (e.g. everything above the major diagonal), the graph should be a comparison of just the **two** WV Implied. 
    * These plots should only contain WV Implied by the model.
    * Please use the same color for each WV Implied that can be found on the diagonal.
    * This should be applied to each row and column that have $i < j$ e.g. 1x2 (model 1 vs. model 2), 1x3 (model 1 vs. model 3), 2x3 (model 2 vs. model 3)

**Comment by Wenchao-Yang** [comment]
PR #101 re-writed this function simply using ggplot2. The dependency on gridExtra can be removed later.

**Comment by coatless** [comment]
From PR #101 

Please update the commit to deal with the following:

- Remove the:

    1. old compare.model2
    2. gridExtra dependency 
    3. commented out code

- Change the construction of the data.frame
   * why was there a switch from the data.frame() build to individually entering elements? This slows the function especially since you are regenerating the index each time (e.g. [t:(t+d-1)),"name"] )

**Comment by coatless** [comment]
Q: How to dynamically name a column?
Related to: https://github.com/SMAC-Group/gmwm/blob/f04cd341b3f0fd92278b9226a832e13c56ff6088/R/GMWM.R#L1811-L1819

A: There is no easy way within `data.frame()` construction.

Normal approach would be:

```r 
var.name = "Wenchao"
Wenchao  = "hi!"
eval(as.symbol(var.name))
```
Though, this fails when embedding into a data.frame.

Best way to move forward is to specify the columns, e.g.:
```r
obj[t:(t+d-1),c('WV','scales','low','high','dataset_h','dataset_v',nom[i])] = data.frame() 
```
