### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/gmwm#75]
Hi guys,

Just a quick question: How can I impose the optimism to based on the same covariance matrix when comparing two models? For example:

model = AR1(phi = 0.9, sigma2 = 1) + DR(slope = 0.01)
Xt = gen.ts(model)
mod1 = gmwm(AR1(), Xt)
mod2 = gmwm(AR1() + DR(), Xt)
summary(mod1, bs.optimism = FALSE)
summary(mod2, bs.optimism = FALSE)

The model score is based on two different covariance matrices. Also, could we easily construct an equivalent to the anova() function in the nlme package? In that function we could compare two (or more?) models by their model score based on the same covariance matrix (obtained by parametric bootstrap under the largest candidate) and possibly add some gof results. Please let me know what you think about it.

Thanks,

Stef

**Comment by coatless** [comment]
@stephaneguerrier Does the rank.models obj output work?

e.g. 
obj.fun, (bootstrap) optimism, criterion, gof

**Comment by coatless** [comment]
Finished with rank.models
