### ISSUE TITLE
Revamp of Decomp Procedures

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#96]
**Issue:**

The decomp procedures are not very user friendly to... well, use. So we need to make them a bit more friendly.

**Solution:**

1. Rewrite the base modwt and dwt function
* Embed brick_wall as a default option
* Filter selection
* J levels of decomp
2. Redo the avar wrapper
* Provide a switch between "mo" and "to" overlaps.
3. Open wvar up to accommodate decomp (dwt and modwt)
* Allows for nlevels
* Filter type. 
* etc

**Comment by coatless** [comment]
@avinash2692 I think this is write up your alley. It will give you an introduction to both wavelet transforms and R/C++ programming.

**Comment by avinash2692** [comment]
@coatless ... will do
