### ISSUE TITLE
Add explanantion on frequency conversion

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/gmwm#98]
Update documentation for wvar, plot.wvar, imu, wvar.imu, plot.wvar.imu to explain how to midify the frequency of the data. For IMU, the default should (I think) be 100Hz. Also, in the object "imu" there should be a filed for the frequency. @coatless can you address this problem?

**Comment by coatless** [comment]
Added `freq` to `imu` in 286da8daf545788b591814e1a8dba3526ee7b75a

wvar plot still needs to be updated with `freq` scaling.

**Comment by coatless** [comment]
Addressed `imu` default frequency and graph scaling.
